import {
    Biotech,
    FileDownload,
    Hub,
    QueryStats,
    Search,
    Storage,
} from '@mui/icons-material';

export const RELEASE_LOG_ANCHOR = 'release-log';

export const releaseEntries = [
    {
        date: 'Mar 15, 2026',
        label: 'Foundation',
        title: 'Trait browser baseline',
        summary: 'Trait browsing moved from rough wiring into a usable flow with browse, trait detail, and the first paged GWAS table.',
        note: 'This was the point where the app stopped feeling like a schema demo and started behaving like a real browser.',
        icon: Storage,
        color: '#2563eb',
    },
    {
        date: 'Mar 29, 2026',
        label: 'Metadata',
        title: 'Schema and trait context tightened up',
        summary: 'Metadata fields, source naming, and collection notes were cleaned up so each trait page could carry more context without extra clicks.',
        note: 'This milestone is intentionally written as a release note rather than a literal commit replay.',
        icon: QueryStats,
        color: '#0f766e',
    },
    {
        date: 'Apr 12, 2026',
        label: 'Delivery',
        title: 'Download paths became dependable',
        summary: 'Result-file discovery and download experiments were pulled into a clearer path, making it easier to move from figures back to raw outputs.',
        note: 'That groundwork later fed directly into the Data Browser experience.',
        icon: FileDownload,
        color: '#b45309',
    },
    {
        date: 'Apr 26, 2026',
        label: 'Rendering',
        title: 'Cross-page rendering pass',
        summary: 'Tables, cards, and route-level layouts were normalized so figure pages could share one visual rhythm instead of drifting page by page.',
        note: 'Think of this as the stability release before the heavier figure work arrived.',
        icon: Search,
        color: '#7c3aed',
    },
    {
        date: 'May 09, 2026',
        label: 'Programs',
        title: 'Program and regulator views arrived',
        summary: 'Program-regulator plots introduced a second lens on the trait signal, adding structure beyond the single-variant view.',
        note: 'This is where the app first started to feel genuinely multi-view.',
        icon: Hub,
        color: '#0284c7',
    },
    {
        date: 'May 20, 2026',
        label: 'Figures',
        title: 'Manhattan and volcano views matured',
        summary: 'The figure layer expanded fast: GWAS Manhattan, burden volcano, and related cleanup made the featured trait page feel analysis-ready.',
        note: 'Several small fix commits around this date are folded into one readable release moment.',
        icon: QueryStats,
        color: '#ea580c',
    },
    {
        date: 'May 27, 2026',
        label: 'Genes',
        title: 'Gene evidence and trait-program links deepened',
        summary: 'Gene-level evidence views landed alongside a stronger trait-program graph, connecting variant signals back to interpretable biology.',
        note: 'This release bundles the gene, graph, and trait-program work into one story.',
        icon: Biotech,
        color: '#7c3aed',
    },
    {
        date: 'May 29, 2026',
        label: 'Compare',
        title: 'Cross-trait heatmaps opened comparative reading',
        summary: 'Heatmap views made it easier to scan how gene effects repeat or diverge across related traits without leaving the main exploration flow.',
        note: 'It is the first release in the log built explicitly around comparison instead of inspection.',
        icon: QueryStats,
        color: '#c2410c',
    },
    {
        date: 'Jun 03, 2026',
        label: 'Home',
        title: 'Search-led home page refresh',
        summary: 'The landing page was reworked around faster entry points, featured figures, and lighter search paths into the result archive.',
        note: 'This release block itself is part of that pass.',
        icon: Search,
        color: '#ff6b4a',
    },
];
